# A sample Gemfile
source "https://rubygems.org"

ruby "2.1.2"

gem 'sinatra', '1.4.5', require: 'sinatra/base'
gem 'redis',  '3.1.0'

# only used in development locally
group :development do
  gem 'shotgun'
  gem 'pry'
end

# gems specific just in the production environment
group :production do
end

group :test do
  gem 'capybara'
  gem 'rspec'
end

